#!/bin/bash

#hdmi or dp
CONNECTION_METHOD=`xrandr | grep -e ' connected' | grep -v eDP | awk '{print $1}'`

#laptop monitor on
if [ "$(cat /sys/class/backlight/intel_backlight/bl_power)" != 0 ]; then
	xrandr --output eDP-1-1 --mode 1920x1080_60.00 --auto --left-of $CONNECTION_METHOD
else #laptop monitor off
	xrandr --output eDP-1-1 --off
	xrandr --output $CONNECTION_METHOD --primary
fi
i3-msg restart
